Document: imgrup
Title: Debian imgrup Manual
Author: <insert document author here>
Abstract: This manual describes what imgrup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/imgrup/imgrup.sgml.gz

Format: postscript
Files: /usr/share/doc/imgrup/imgrup.ps.gz

Format: text
Files: /usr/share/doc/imgrup/imgrup.text.gz

Format: HTML
Index: /usr/share/doc/imgrup/html/index.html
Files: /usr/share/doc/imgrup/html/*.html
